---

name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  static-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Get Hugo
        env:
          HUGO_VERSION: 0.78.1
          HUGO_CHECKSUM: e0d1b3ca30426931084dd6a0abb451be28f6a3dd23d85d87d272a1f95782912d
        run: |
          curl --output /tmp/hugo.tar.gz -fsSL "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
          echo "${HUGO_CHECKSUM}  /tmp/hugo.tar.gz" | sha256sum -c
          tar -xvzf /tmp/hugo.tar.gz -C /tmp hugo
          rm -f /tmp/hugo.tar.gz
          chmod +x /tmp/hugo
          /tmp/hugo version

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout theme
        uses: actions/checkout@v2
        with:
          repository: tristan-weil/hugo-theme-learn
          ref: master
          path: themes/hugo-theme-learn

      - name: Build Static Pages
        run: |
          /tmp/hugo --minify
